/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai;

import java.io.InputStream;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;


/**
 *
 * @author aNawOrLd
 */
public class cnf extends javax.swing.JFrame {
    public Instant start ;
    String arr[];
     JMake jj=new JMake();
    /**
     * Creates new form cnf
     */
    public cnf(String arr[]) {
        this.arr=arr;
        initComponents();
             setLocationRelativeTo(null);
             pic.setIcon(new ImageIcon("assets/otp.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cid = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ppl = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Confirmation of E-mail ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 290, 36));

        cid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cid.setForeground(new java.awt.Color(0, 255, 0));
        cid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cid.setText("adas7579@rediffmail.com");
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 310, 36));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 470, 10));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Enter OTP :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 132, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("OTP Sent To E-mail :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 132, 36));
        getContentPane().add(ppl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 30));

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 80, 30));

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Verify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Haven't Receive OTP yet ?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Resend OTP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 140, 40));
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Are You Sure to want to exit ?","Select Option",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            try {
     jj.delOTP(arr[0]);
    } catch (Exception ex) {
        Logger.getLogger(cnf.class.getName()).log(Level.SEVERE, null, ex);
    }
            Reg tt=new Reg();
            tt.setVisible(true);this.setVisible(false);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Instant end = Instant.now();
Duration timeElapsed = Duration.between(start, end);
System.out.println("Time taken: "+ timeElapsed.toMinutes() +"minutes");
if(timeElapsed.toMinutes()>9)
{
    try {
     jj.delOTP(arr[0]);
     JOptionPane.showMessageDialog(null, "OTP Expired!","Error",2);
            this.setVisible(false);
            Reg rg=new Reg();
            rg.setVisible(true);
    } catch (Exception ex) {
        Logger.getLogger(cnf.class.getName()).log(Level.SEVERE, null, ex);
    }
}
            


       
        int res = 0;
        try {
            res=jj.cnfOTP(new String[]{arr[0],ppl.getText()});
        } catch (Exception ex) {
            Logger.getLogger(cnf.class.getName()).log(Level.SEVERE, null, ex);
        }


        if(res==1)
        {
        
           int cc= jj.Reg(arr);
       if(cc==1){    
       
            try {
                 String s = "";
        try {
            Process child = Runtime.getRuntime().exec("wmic csproduct get uuid");

            InputStream in = child.getInputStream();
         
            int c;
            while ((c = in.read()) != -1) {
                //System.out.print((char) c);
                s = s + (char) c;
            }
            System.out.println(s);
            s = s.substring(4);
            s = s.trim();
            System.out.println(s);
            in.close();

        } catch (Exception ex) {
        }
                JSONObject i=jj.Login(arr[0], arr[1],s);
                if (i.containsValue("Device Not Registered")) {
                String a[] = new String[]{System.getProperty("os.name"),arr[0],s,System.getProperty("user.name")+s.substring(14,18)};
                
              int re=jj.RegDevice(a);
                 if(re==0)                  
                 {
                 JOptionPane.showMessageDialog(null, "Device Already Binded!","Warning",2);
                 System.exit(0);
                 }
                 else{
                  JSONObject yy=   jj.Login(arr[0], arr[1],s);
                  this.setVisible(false);                
                welcome w=new welcome(yy);         
                w.setVisible(true);
                this.setVisible(false);
                 }
                
            } else {
                    
                    JSONObject yy=jj.Login(arr[0], arr[1],s);
                this.setVisible(false);                
                welcome w=new welcome(yy);         
                w.setVisible(true);
                this.setVisible(false);
            }
            } catch (Exception ex) {
                Logger.getLogger(cnf.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            this.setVisible(false);
        }
       else
        {
            JOptionPane.showMessageDialog(null, "Registration UnSuccessful!");
            this.setVisible(false);
            Reg rg=new Reg();
            rg.setVisible(true);
        }
        }
        
       
        else
        {
        JOptionPane.showMessageDialog(null,"Invalid OTP!","Verification Error",2);
       // this.setVisible(false);
      
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
          int i=  jj.resendOTP(arr[0]);
          if(i==1)
              JOptionPane.showMessageDialog(null, "OTP Resend Successfully");
              else
              JOptionPane.showMessageDialog(null, "Unable to send OTP!");
        } catch (Exception ex) {
            Logger.getLogger(cnf.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cnf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
String a[] = null;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cnf(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pic;
    private javax.swing.JPasswordField ppl;
    // End of variables declaration//GEN-END:variables
}
