/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai;

import java.awt.Color;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author aNawOrLd
 */
public class Reg extends javax.swing.JFrame {

    JMake jj = new JMake();

    public Reg() {
        
        initComponents();
        setLocationRelativeTo(null);
        pic.setIcon(new ImageIcon("assets/ipad.jpg"));
        jLabel3.requestFocus();
        ee1.setVisible(false);
        ee2.setVisible(false);
        ee3.setVisible(false);
        ee.setVisible(false);
        ee4.setVisible(false);
        ee5.setVisible(false);
        int y = LocalDateTime.now().getYear();
        
        for (int i = 1; i <= 31; i++) {
            dd.addItem(i + "");
        }
        for (int i = 1; i <= 12; i++) {
            mm.addItem(i + "");
        }
        for (int i = 1980; i <= y; i++) {
            yy.addItem(i + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ee = new javax.swing.JLabel();
        ee1 = new javax.swing.JLabel();
        ee2 = new javax.swing.JLabel();
        ee3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        already = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        untxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pwdtxt = new javax.swing.JPasswordField();
        pwdtx = new javax.swing.JPasswordField();
        fntxt = new javax.swing.JTextField();
        ee4 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();
        yy = new javax.swing.JComboBox<>();
        dd = new javax.swing.JComboBox<>();
        mm = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        ee5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ee.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ee.setForeground(new java.awt.Color(255, 0, 0));
        ee.setText("* Field Cannot be Blank.");
        getContentPane().add(ee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, 120, 20));

        ee1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ee1.setForeground(new java.awt.Color(255, 0, 0));
        ee1.setText("* Field Cannot be Blank.");
        getContentPane().add(ee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 290, 120, 20));

        ee2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ee2.setForeground(new java.awt.Color(255, 0, 0));
        ee2.setText("* Field Cannot be Blank.");
        getContentPane().add(ee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 220, 120, 20));

        ee3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ee3.setForeground(new java.awt.Color(255, 0, 0));
        ee3.setText("* Field Cannot be Blank.");
        getContentPane().add(ee3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 150, 120, 20));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("X");
        jButton4.setToolTipText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 50, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("_");
        jButton3.setToolTipText("Minimise");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 50, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("InArCo : SignUp");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 30, 10, 690));

        jLabel7.setBackground(new java.awt.Color(0, 0, 255));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 10, 690));

        already.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        already.setText("<html><u>Already have an Account!</u></html>");
        already.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alreadyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alreadyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alreadyMouseExited(evt);
            }
        });
        getContentPane().add(already, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 670, 190, 30));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Date-of-Birth");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 520, -1, -1));

        untxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        untxt.setForeground(new java.awt.Color(153, 153, 153));
        untxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        untxt.setText("User Name");
        untxt.setToolTipText("User Name");
        untxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                untxtCaretUpdate(evt);
            }
        });
        untxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                untxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                untxtFocusLost(evt);
            }
        });
        untxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                untxtMouseClicked(evt);
            }
        });
        untxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                untxtActionPerformed(evt);
            }
        });
        untxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                untxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                untxtKeyTyped(evt);
            }
        });
        getContentPane().add(untxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, 330, 40));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                Sign Up");
        jLabel3.setNextFocusableComponent(emtxt);
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 350, -1));

        emtxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        emtxt.setForeground(new java.awt.Color(153, 153, 153));
        emtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emtxt.setText("Enter E-mail ID");
        emtxt.setToolTipText("E-mail");
        emtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emtxtFocusLost(evt);
            }
        });
        emtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emtxtMouseClicked(evt);
            }
        });
        getContentPane().add(emtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 330, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><font color=\"blue\"><font face=\"monotype corsiva\">Welcome</font> to</font><font color=\"blue\"> InArCo</font></html?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 440, 80));

        pwdtxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pwdtxt.setForeground(new java.awt.Color(153, 153, 153));
        pwdtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwdtxt.setText("Enter Password");
        pwdtxt.setToolTipText("Password");
        pwdtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdtxt.setEchoChar('\u0000');
        pwdtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdtxtFocusLost(evt);
            }
        });
        pwdtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdtxtMouseClicked(evt);
            }
        });
        getContentPane().add(pwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, 330, 40));

        pwdtx.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pwdtx.setForeground(new java.awt.Color(153, 153, 153));
        pwdtx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwdtx.setText("Re-Enter Password");
        pwdtx.setToolTipText("Re-Enter Password");
        pwdtx.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdtx.setEchoChar('\u0000');
        pwdtx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdtxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdtxFocusLost(evt);
            }
        });
        pwdtx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdtxMouseClicked(evt);
            }
        });
        getContentPane().add(pwdtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 330, 40));

        fntxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fntxt.setForeground(new java.awt.Color(153, 153, 153));
        fntxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fntxt.setText("Full Name");
        fntxt.setToolTipText("Full Name");
        fntxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fntxtCaretUpdate(evt);
            }
        });
        fntxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fntxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fntxtFocusLost(evt);
            }
        });
        fntxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fntxtMouseClicked(evt);
            }
        });
        fntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntxtActionPerformed(evt);
            }
        });
        fntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fntxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fntxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fntxtKeyTyped(evt);
            }
        });
        getContentPane().add(fntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 330, 40));

        ee4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ee4.setForeground(new java.awt.Color(255, 0, 0));
        ee4.setText("* Field Cannot be Blank.");
        getContentPane().add(ee4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 480, 120, 20));

        gen.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                     $<  Select Gender  >$", "Male", "Female" }));
        getContentPane().add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, 330, 40));

        yy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yyItemStateChanged(evt);
            }
        });
        yy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yyFocusLost(evt);
            }
        });
        getContentPane().add(yy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 80, 30));

        dd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ddFocusLost(evt);
            }
        });
        getContentPane().add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 80, 30));

        mm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mmItemStateChanged(evt);
            }
        });
        mm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mmFocusLost(evt);
            }
        });
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });
        getContentPane().add(mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 80, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 350, -1));

        ee5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        ee5.setForeground(new java.awt.Color(255, 0, 0));
        ee5.setText("* Field Cannot be Blank.");
        getContentPane().add(ee5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 410, 120, 20));

        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setText("Register");
        jButton2.setNextFocusableComponent(jLabel3);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 630, 330, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 2, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 370, 660));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Just few steps more to make you ready");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 360, 40));

        pic.setIcon(new javax.swing.ImageIcon("E:\\vero\\AI\\assets\\ipad.jpg")); // NOI18N
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1260, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emtxtMouseClicked

    }//GEN-LAST:event_emtxtMouseClicked
    

    private void pwdtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdtxtMouseClicked
//        //if(txtpss.getPassword().equals("Password"))
//        {
//            pwdtxt.setText("");
//            pwdtxt.setEchoChar('\u25cf');
//            pwdtxt.setForeground(Color.BLACK);
//        }
    }//GEN-LAST:event_pwdtxtMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (emtxt.getText().equalsIgnoreCase("Enter E-mail id")) {
            ee3.setVisible(true);
            return;
        } else {
            ee3.setVisible(false);
            
            
        }
        
        if (pwdtxt.getText().equalsIgnoreCase("Enter Password")) {
            ee2.setVisible(true);
            return;
        } else {
            ee2.setVisible(false);
        }
        
        if (pwdtx.getText().equalsIgnoreCase("Re-Enter Password")) {
            ee1.setVisible(true);
            return;
        } else {
            ee1.setVisible(false);
        }
        
        if (untxt.getText().equalsIgnoreCase("User Name")) {
            ee.setVisible(true);
            return;
        } else {
            ee.setVisible(false);
        }
        
        if (fntxt.getText().equalsIgnoreCase("Full Name")) {
            ee5.setVisible(true);
            return;
        } else {
            ee5.setVisible(false);
        }
        
        if (gen.getSelectedIndex() == 0) {
            ee4.setVisible(true);
            return;
        } else {
            ee4.setVisible(false);
        }
        
        if (!pwdtxt.getText().equals(pwdtx.getText())) {
            JOptionPane.showMessageDialog(null, "Password Did't Match", "Message", 2);
            pwdtxt.setText("");
            pwdtx.setText("");
            return;
        }
        if(pwdtxt.getText().length()<8)
        {
          JOptionPane.showMessageDialog(null, "Password should be minimum 8 character!", "Message", 2);
          return;
        }
        
        String po = untxt.getText().toUpperCase();
        if (ee.isVisible() == false && ee1.isVisible() == false && ee2.isVisible() == false && ee3.isVisible() == false && pwdtxt.getText().equals(pwdtx.getText())) {
            String da = dd.getSelectedItem().toString() + "/" + mm.getSelectedItem().toString() + "/" + yy.getSelectedItem().toString();
            String a[] = new String[]{emtxt.getText(), pwdtxt.getText(), po, fntxt.getText(), gen.getSelectedItem().toString(), da};

            //   int otp = (int) Math.floor(Math.random() * (999999 - 100000 + 1)) + 100000;
            //   SendEmail mailobj = new SendEmail();
            //   mailobj.sendMail(emtxt.getText(), "InArCo Email Verification", "Hello " + fntxt.getText().toUpperCase() + "\nUse following OTP to confirm your Email: \nYour OTP is : " + otp + "\nIf you didn’t ask to verify this address, you can ignore this email.\nThanks\nTeam InArCo");
            this.setVisible(false);
            
            JMake jj = new JMake();
            try {
                int res = jj.getOTP(a[0]);
                if (res == 1) {
                    cnf ff = new cnf(a);
                    LocalTime time = LocalTime.now();                    
                    System.out.println(time);
                    ff.start = Instant.now();
                    ff.cid.setText(a[0]);
                    ff.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Failed To sent OTP!");
                    
                }
            } catch (Exception ex) {
                Logger.getLogger(Reg.class.getName()).log(Level.SEVERE, null, ex);
            }
            //     ff.otp = otp;
            
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void untxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_untxtMouseClicked
        if (untxt.getText().equals("user Name")) {
            untxt.setText("");
        }

    }//GEN-LAST:event_untxtMouseClicked

    private void untxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_untxtKeyPressed
        

    }//GEN-LAST:event_untxtKeyPressed

    private void untxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_untxtActionPerformed

    }//GEN-LAST:event_untxtActionPerformed

    private void untxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_untxtFocusGained
        if (untxt.getText().equals("User Name")) {
            untxt.setText("");
            untxt.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_untxtFocusGained

    private void untxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_untxtFocusLost
if(!Pattern.matches("/[^A-Z0-9_@.]/g",untxt.getText()))
{
      JOptionPane.showMessageDialog(null,"Invalid Username");
    return;
}
        if (untxt.getText().equals("")) {
            untxt.setText("User Name");
            untxt.setForeground(new Color(153,153,153));
        } else {
            try {
                int i = jj.Validate(untxt.getText(), 1);
                if (i != 1) {
                    JOptionPane.showMessageDialog(null, "UserName already Registered!");
                }
            } catch (Exception ex) {
                Logger.getLogger(Reg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_untxtFocusLost

    private void emtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emtxtFocusGained
        if (emtxt.getText().equals("Enter E-mail ID")) {
            emtxt.setText("");
            emtxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_emtxtFocusGained

    private void emtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emtxtFocusLost
if(!Pattern.matches("([\\d\\w]+[.\\w\\d])+?([.\\w\\d])?@([\\w\\d]+[.\\w\\d]*)",emtxt.getText()))
{
      JOptionPane.showMessageDialog(null,"Invalid Email");
    return;
}
        if (emtxt.getText().equals("")) {
            emtxt.setText("Enter E-mail ID");
            emtxt.setForeground(new Color(153,153,153));
        } else {
            try {
                int i = jj.Validate(emtxt.getText(), 0);
                if (i != 1) {
                    JOptionPane.showMessageDialog(null, "Email Already Registered!");
                    emtxt.setText("");
                    emtxt.requestFocus();
                }
            } catch (Exception ex) {
                Logger.getLogger(Reg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_emtxtFocusLost

    private void pwdtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdtxtFocusGained
        String h = new String(pwdtxt.getPassword());
        if (h.equals("Enter Password")) {
            pwdtxt.setText("");            
            pwdtxt.setEchoChar('\u25cf');
            pwdtxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pwdtxtFocusGained

    private void pwdtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdtxtFocusLost
if(!Pattern.matches("/((?=.\\d)(?=.[a-z])(?=.[A-Z])(?=.[\\W]).{8,64})/g",pwdtxt.getText()))
{
      JOptionPane.showMessageDialog(null,"Invalid Password");
    return;
}
        String h = new String(pwdtxt.getPassword());
        if (h.equals("")) {
            pwdtxt.setText("Enter Password");
            pwdtxt.setEchoChar('\0');
            pwdtxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pwdtxtFocusLost

    private void untxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_untxtCaretUpdate

    }//GEN-LAST:event_untxtCaretUpdate

    private void untxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_untxtKeyTyped

    }//GEN-LAST:event_untxtKeyTyped

    private void alreadyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyMouseClicked
        this.setVisible(false);
        Home lg = new Home();
        lg.setVisible(true);

    }//GEN-LAST:event_alreadyMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fntxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fntxtCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_fntxtCaretUpdate

    private void fntxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fntxtFocusGained
        if (fntxt.getText().equals("Full Name")) {
            fntxt.setText("");
            fntxt.setForeground(Color.BLACK);
        }        
    }//GEN-LAST:event_fntxtFocusGained

    private void fntxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fntxtFocusLost
if(!Pattern.matches("/[^A-Za-z ]/g",fntxt.getText()))
{
JOptionPane.showMessageDialog(null,"Invalid FullName");
    return;
}
        if (fntxt.getText().equals("")) {
            fntxt.setText("Full Name");
            fntxt.setForeground(new Color(153,153,153));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fntxtFocusLost

    private void fntxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fntxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fntxtMouseClicked

    private void fntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fntxtActionPerformed

    private void fntxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fntxtKeyPressed
        
    }//GEN-LAST:event_fntxtKeyPressed

    private void fntxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fntxtKeyTyped
        if (!Character.isLetter(evt.getKeyChar()) && !Character.isWhitespace(evt.getKeyChar())) {
            evt.setKeyChar('\0');
        }
    }//GEN-LAST:event_fntxtKeyTyped

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void mmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mmItemStateChanged
        
        int a = Integer.parseInt(mm.getSelectedItem().toString());
        if (a == 4 || a == 6 || a == 9 || a == 11) {
            dd.removeAllItems();
            for (int i = 1; i <= 30; i++) {
                dd.addItem(i + "");
            }
        } else if (a == 2) {
            int y = Integer.parseInt(yy.getSelectedItem().toString());
            
            if (((y % 4 == 0) && (y % 100 != 0)) || (y % 400 == 0)) {
                dd.removeAllItems();
                for (int i = 1; i <= 29; i++) {
                    dd.addItem(i + "");
                }
            } else {
                dd.removeAllItems();
                for (int i = 1; i <= 28; i++) {
                    dd.addItem(i + "");
                }
            }
        } else {
            dd.removeAllItems();
            for (int i = 1; i <= 31; i++) {
                dd.addItem(i + "");
            }
        }
    }//GEN-LAST:event_mmItemStateChanged

    private void yyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yyItemStateChanged
        int a = Integer.parseInt(yy.getSelectedItem().toString());
        
        if (Integer.parseInt(mm.getSelectedItem().toString()) == 2) {
            if (((a % 4 == 0) && (a % 100 != 0)) || (a % 400 == 0)) {
                dd.removeAllItems();
                for (int i = 1; i <= 29; i++) {
                    dd.addItem(i + "");
                }
            } else {
                dd.removeAllItems();
                for (int i = 1; i <= 28; i++) {
                    dd.addItem(i + "");
                }
            }
        }
    }//GEN-LAST:event_yyItemStateChanged

    private void ddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ddFocusLost
        int d = Integer.parseInt(dd.getSelectedItem().toString());
        int m = Integer.parseInt(mm.getSelectedItem().toString());
        int y = Integer.parseInt(yy.getSelectedItem().toString());
        if (d == LocalDateTime.now().getDayOfMonth() && m == LocalDateTime.now().getMonthValue() && y == LocalDateTime.now().getYear()) {
            JOptionPane.showMessageDialog(null, "The date-of-birth you've entered doesn't seem to be correct!");
        }
    }//GEN-LAST:event_ddFocusLost

    private void mmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mmFocusLost
        int d = Integer.parseInt(dd.getSelectedItem().toString());
        int m = Integer.parseInt(mm.getSelectedItem().toString());
        int y = Integer.parseInt(yy.getSelectedItem().toString());
        if (d == LocalDateTime.now().getDayOfMonth() && m == LocalDateTime.now().getMonthValue() && y == LocalDateTime.now().getYear()) {
            JOptionPane.showMessageDialog(null, "The date-of-birth you've entered doesn't seem to be correct!");
        }
    }//GEN-LAST:event_mmFocusLost

    private void yyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yyFocusLost
        int d = Integer.parseInt(dd.getSelectedItem().toString());
        int m = Integer.parseInt(mm.getSelectedItem().toString());
        int y = Integer.parseInt(yy.getSelectedItem().toString());
        if (d == LocalDateTime.now().getDayOfMonth() && m == LocalDateTime.now().getMonthValue() && y == LocalDateTime.now().getYear()) {
            JOptionPane.showMessageDialog(null, "The date-of-birth you've entered doesn't seem to be correct!");
        }
    }//GEN-LAST:event_yyFocusLost

    private void alreadyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyMouseEntered
        already.setForeground(Color.RED);
    }//GEN-LAST:event_alreadyMouseEntered

    private void alreadyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alreadyMouseExited
        already.setForeground(Color.BLACK);
    }//GEN-LAST:event_alreadyMouseExited

    private void fntxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fntxtKeyReleased
        

    }//GEN-LAST:event_fntxtKeyReleased

    private void pwdtxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdtxFocusGained
        String h = new String(pwdtx.getPassword());
        if (h.equals("Re-Enter Password")) {
            pwdtx.setText("");            
            pwdtx.setEchoChar('\u25cf');
            pwdtx.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pwdtxFocusGained

    private void pwdtxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdtxFocusLost
if(!Pattern.matches("/((?=.\\d)(?=.[a-z])(?=.[A-Z])(?=.[\\W]).{8,64})/g",pwdtx.getText()))
{
      JOptionPane.showMessageDialog(null,"Invalid Password");
    return;
}
        String h = new String(pwdtx.getPassword());
        if (h.equals("")) {
            pwdtx.setText("Re-Enter Password");
            pwdtx.setEchoChar('\0');
            pwdtx.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pwdtxFocusLost

    private void pwdtxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdtxMouseClicked
//        pwdtx.setText("");
//        pwdtx.setEchoChar('\u25cf');
//        pwdtx.setForeground(Color.BLACK);
    }//GEN-LAST:event_pwdtxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel already;
    private javax.swing.JComboBox<String> dd;
    private javax.swing.JLabel ee;
    private javax.swing.JLabel ee1;
    private javax.swing.JLabel ee2;
    private javax.swing.JLabel ee3;
    private javax.swing.JLabel ee4;
    private javax.swing.JLabel ee5;
    private javax.swing.JTextField emtxt;
    private javax.swing.JTextField fntxt;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> mm;
    private javax.swing.JLabel pic;
    private javax.swing.JPasswordField pwdtx;
    private javax.swing.JPasswordField pwdtxt;
    private javax.swing.JTextField untxt;
    private javax.swing.JComboBox<String> yy;
    // End of variables declaration//GEN-END:variables
}
