/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai;

import java.awt.AWTException;
import java.awt.CheckboxMenuItem;
import java.awt.Menu;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.io.InputStream;
import java.time.Instant;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author ULTRON
 */
public class splash extends javax.swing.JFrame {

    static int te = 0;

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
        bc.setIcon(new ImageIcon("assets/splash.gif"));
        
        
        

        
        
        
        
        
        
        
//        DB bb=new DB("1");
//        bb.newuser(a);
//        try {
//           DB dd=new DB("1");
//        dd.open();
//      ResultSet rs=  dd.getData("select * from login");
//       while(rs.next())
//       {
//        System.out.print(rs.getString("id")+rs.getString("pwd")+rs.getString("did"));
//       }
//       dd.close();
//        } catch (Exception ex) {
//            Logger.getLogger(splash.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
        System.out.print(Instant.now());
      
        check();

        //C:\Users\aNaWorLd\AppData\Roaming\Microsoft\Windows\Recent
        //C:\ProgramData\Microsoft\Windows\Start Menu\Programs
        try {
            Process child = Runtime.getRuntime().exec("wmic csproduct get uuid");

            InputStream in = child.getInputStream();
            String s = "";
            int c;
            while ((c = in.read()) != -1) {
                System.out.print((char) c);
                s = s + (char) c;
            }
            System.out.println(s);
            s = s.substring(4);
            s = s.trim();

            in.close();

        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("iTs noThiNg liKe anYthInG...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        jLabel2.setFont(new java.awt.Font("Space Bd BT", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("InArCo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        bc.setIcon(new javax.swing.ImageIcon("M:\\AI\\assets\\splash.gif")); // NOI18N
        getContentPane().add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    void check() {
        try {
            Process child = Runtime.getRuntime().exec("cmd /c jps");

            InputStream in = child.getInputStream();
            String s = "";
            int c;
            while ((c = in.read()) != -1) {
                System.out.print((char) c);
                s = s + (char) c;
            }

           

            // bc.setText(s);
            System.out.println(s);
            in.close();
            if (s.indexOf("splash") != s.lastIndexOf("splash") || s.indexOf("AI.jar") != s.lastIndexOf("AI.jar")) {
                te = 1;
                JOptionPane.showMessageDialog(null, "Another instance of the same application already running!");
                System.exit(0);
            }
        } catch (Exception ex) {
        }
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated


    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new splash().setVisible(true);

            }
        });
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(splash.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (te == 0) {
            
            remem r = new remem();
            if (r.dec() != null) {
                JSONObject i = null;
                String s[] = r.dec();
                JMake jj = new JMake();
                try {
                    i = jj.Login(s[1], s[2], s[3]);
                    welcome nn = new welcome(i);
                    nn.pass = s[2];
                    nn.setVisible(true);
                    splash.getWindows()[0].setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(splash.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                Home h = new Home();
                h.setVisible(true);
                splash.getWindows()[0].setVisible(false);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
