/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Anagrams.java
 *
 * Created on Sep 13, 2015, 4:18:36 PM
 */
package Games;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ANADI
 */
public class KBC extends javax.swing.JFrame {

    String ans = "";

    int r = 0;
String we;
String j="";
int o1;
/** Creates new form Anagrams */
    public KBC() {


 
        initComponents();
        wr();
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m1 = new javax.swing.JDesktopPane();
        b1 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        a2 = new javax.swing.JRadioButton();
        a3 = new javax.swing.JRadioButton();
        a4 = new javax.swing.JRadioButton();
        a1 = new javax.swing.JRadioButton();
        st = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JList();
        q2 = new javax.swing.JPanel();
        q3 = new javax.swing.JPanel();
        qu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        q1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        m1.setBackground(new java.awt.Color(51, 51, 51));
        m1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(246, 239, 239));
        b1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(204, 102, 0)));
        m1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 990, 90));

        jDesktopPane2.setBackground(new java.awt.Color(51, 255, 255));

        a2.setBackground(new java.awt.Color(51, 51, 51));
        a2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setText("B)");
        a2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 153, 0)));
        a2.setFocusable(false);
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(a2);
        a2.setBounds(500, 0, 490, 110);

        a3.setBackground(new java.awt.Color(51, 51, 51));
        a3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setText("C)");
        a3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 153, 0)));
        a3.setFocusable(false);
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(a3);
        a3.setBounds(0, 110, 500, 120);

        a4.setBackground(new java.awt.Color(51, 51, 51));
        a4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setText("D)");
        a4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 153, 0)));
        a4.setFocusable(false);
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(a4);
        a4.setBounds(500, 110, 490, 120);

        a1.setBackground(new java.awt.Color(51, 51, 51));
        a1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setText("A)");
        a1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 204, 204)));
        a1.setFocusable(false);
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a1MouseEntered(evt);
            }
        });
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(a1);
        a1.setBounds(0, 0, 500, 110);

        m1.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 990, 230));

        st.setBackground(new java.awt.Color(153, 255, 153));
        st.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        st.setMnemonic('s');
        st.setText("START");
        st.setFocusable(false);
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        m1.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 303, 100, 50));

        l1.setBackground(new java.awt.Color(153, 255, 255));
        l1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(15, 1, 1));
        l1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "10   <>     1000", "9     <>     800  ", "8     <>     700", "7     <>     600", "6     <>     500", "5     <>     400", "4     <>     300", "3     <>     200", "2     <>     100", "1     <>     10\t     " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        l1.setEnabled(false);
        l1.setSelectedIndex(9);
        l1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        l1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(l1);

        m1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 160, 250));

        q2.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout q2Layout = new javax.swing.GroupLayout(q2);
        q2.setLayout(q2Layout);
        q2Layout.setHorizontalGroup(
            q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        q2Layout.setVerticalGroup(
            q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        m1.add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        q3.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout q3Layout = new javax.swing.GroupLayout(q3);
        q3.setLayout(q3Layout);
        q3Layout.setHorizontalGroup(
            q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        q3Layout.setVerticalGroup(
            q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        m1.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        qu.setBackground(new java.awt.Color(255, 0, 51));
        qu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        qu.setForeground(new java.awt.Color(255, 255, 255));
        qu.setText("QUIT");
        qu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quActionPerformed(evt);
            }
        });
        m1.add(qu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 80, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WRONG ANSWER");
        m1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOCK ANSWER");
        m1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WRIGHT ANSWER");
        m1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, 30));

        q1.setBackground(new java.awt.Color(255, 102, 0));
        q1.setOpaque(true);
        m1.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(m1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
o1=0;

        //a1

        String op = a1.getText();


        ans = op;
        int q = l1.getSelectedIndex();
        if (q == 9) {
            Color as = q1.getBackground();
            a1.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("a) bangalore")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(8);s();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right");
                    qu.setVisible(true);wr();
                    sh();
                } else if (ans.equalsIgnoreCase("a) lo")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(8);s();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right");
                    qu.setVisible(true);wr();
                     sh();
                } else {
                    Color qw = q3.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();
                    wr();

                }


            } else {
                re();
                a1.setSelected(false);
            }
        }
        if (q == 8) {
            Color as = q1.getBackground();
            a1.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {


                if (ans.equalsIgnoreCase("A) The Scorpion King")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(7);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right");
                     sh();wr();
                } else {
                    Color qw = q3.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(9);r();
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);
wr();
                }


            } else {
                re();
                a1.setSelected(false);
            }
        }
        if (q == 7) {
            Color as = q1.getBackground();
            a1.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {


                if (ans.equalsIgnoreCase("A) February 9, 2005")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(6);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                } else if (ans.equalsIgnoreCase("A) MADHYA PRADESH")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(6);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                } else {
                    Color qw = q3.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();
wr();
                }


            } else {
                re();
                a1.setSelected(false);
            }
        }
//
       if (q == 6) {
            Color as = q1.getBackground();
            a1.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {


                if (ans.equalsIgnoreCase("A) ppm")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(5);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right");
                     sh();wr();
                } else {
                    Color qw = q3.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(9);r();
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);
wr();
                }


            } else {
                re();
                a1.setSelected(false);
            }
        }
        if (q == 5) {
            Color as = q1.getBackground();
            a1.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {


                if (ans.equalsIgnoreCase("A) vatican city")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(4);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                } else if (ans.equalsIgnoreCase("A) rupiah")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(4);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                } else {
                    Color qw = q3.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();
wr();
                }


            } else {
                re();
                a1.setSelected(false);
            }
        }
         if (q == 4) {
            Color as = q1.getBackground();
            a1.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {


                if (ans.equalsIgnoreCase("A) It's your world!")) {
                    Color qw = q2.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(3);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right");
                     sh();wr();
                } else {
                    Color qw = q3.getBackground();
                    a1.setBackground(qw);
                    l1.setSelectedIndex(9);r();
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);
wr();
                }


            } else {
                re();
                a1.setSelected(false);
            }
        }


}//GEN-LAST:event_a1ActionPerformed

    private void a1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseEntered
    }//GEN-LAST:event_a1MouseEntered

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
o1=0;//a2

        String op = a2.getText();
        ans = op;
        int q = l1.getSelectedIndex();
        if (q == 9) {
            Color as = q1.getBackground();
            a2.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("b) intel 4004")) {
                    Color qw = q2.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(8);s();
                    JOptionPane.showMessageDialog(null, "Congatulations!\nYour Answer is Right"); sh();wr();
                    qu.setVisible(true);
                } else {
                    Color qw = q3.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }
            } else {
                re();
                a2.setSelected(false);
            }

        }
        if (q == 8) {
            Color as = q1.getBackground();
            a2.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("b) 1 MHz")) {
                    Color qw = q2.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(7);
                    JOptionPane.showMessageDialog(null, "Congatulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }
            } else {
                re();
                a2.setSelected(false);
            }

        }

 if (q == 7) {
            Color as = q1.getBackground();
            a2.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {


                    Color qw = q3.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();

            } else {
                re();
                a2.setSelected(false);
            }

        }
if (q == 6) {
            Color as = q1.getBackground();
            a2.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {


                    Color qw = q3.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();

            } else {
                re();
                a2.setSelected(false);
            }

        }
        if (q == 5) {
            Color as = q1.getBackground();
            a2.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("b) October 24, 1945")) {
                    Color qw = q2.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(4);
                    JOptionPane.showMessageDialog(null, "Congatulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }
            } else {
                re();
                a2.setSelected(false);
            }

        }
        if (q == 4) {
            Color as = q1.getBackground();
            a2.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("b) Indian Statistical Institute, Kolkata")) {
                    Color qw = q2.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(3);
                    JOptionPane.showMessageDialog(null, "Congatulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a2.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }
            } else {
                re();
                a2.setSelected(false);
            }

        }
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
o1=0;//a3

        String op = a3.getText();
        ans = op;
        int q = l1.getSelectedIndex();
        if (q == 9) {
            Color as = q1.getBackground();
            a3.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("c) SANGARSH")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(8);s();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                    qu.setVisible(true);
                } else {
                    Color qw = q3.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a3.setSelected(false);
            }
        }
        if (q == 8) {
            Color as = q1.getBackground();
            a3.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("c) OCTOBER 1997")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(7);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else if (ans.equalsIgnoreCase("c) hotmail")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(7);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a3.setSelected(false);
            }
        }
        if (q == 7) {
            Color as = q1.getBackground();
            a3.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("c) CALIFORNIA")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(6);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                }
                else if (ans.equalsIgnoreCase("c) ANUPAM KHER")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(6);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a3.setSelected(false);
            }
        }

if (q == 6) {
            Color as = q1.getBackground();
            a3.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("c) Bps")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(5);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else if (ans.equalsIgnoreCase("c) 3,000")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(5);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a3.setSelected(false);
            }
        }

if (q == 5) {
            Color as = q1.getBackground();
            a3.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("c) Brussels")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(4);s();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                    qu.setVisible(true);
                } 
                if (ans.equalsIgnoreCase("c) The hague")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(4);s();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                    qu.setVisible(true);
                } 
                else {
                    Color qw = q3.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a3.setSelected(false);
            }
        }

if (q == 4) {
            Color as = q1.getBackground();
            a3.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("c) Nepal")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(3);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else if (ans.equalsIgnoreCase("c) geneva")) {
                    Color qw = q2.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(3);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a3.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a3.setSelected(false);
            }
        }







    // // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
o1=0;//a4

        String op = a4.getText();
        ans = op;
        int q = l1.getSelectedIndex();
        if (q == 9) {
            Color as = q1.getBackground();
            a4.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("d) BOOKER TERRIFERO WASHINGTON")) {
                    Color qw = q2.getBackground();

                    a4.setBackground(qw);
                    l1.setSelectedIndex(8);s();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();
                    qu.setVisible(true);
                } else {
                    Color qw = q3.getBackground();
                    a4.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a4.setSelected(false);
            }
        }
        if (q == 8) {
            Color as = q1.getBackground();
            a4.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("d) mahatma gandhi")) {
                    Color qw = q2.getBackground();

                    a4.setBackground(qw);
                    l1.setSelectedIndex(7);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a4.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a4.setSelected(false);
            }
        }
        if (q == 7) {
            Color as = q1.getBackground();
            a4.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("d) HENNESSEY VENOM GT")) {
                    Color qw = q2.getBackground();

                    a4.setBackground(qw);
                    l1.setSelectedIndex(6);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a4.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a4.setSelected(false);
            }
        }

         if (q == 6) {
            Color as = q1.getBackground();
            a4.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("d) ALL")) {
                    Color qw = q2.getBackground();

                    a4.setBackground(qw);
                    l1.setSelectedIndex(5);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                }
                else  if (ans.equalsIgnoreCase("d) Tool of c")) {
                    Color qw = q2.getBackground();

                    a4.setBackground(qw);
                    l1.setSelectedIndex(5);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                }
                else {
                    Color qw = q3.getBackground();
                    a4.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a4.setSelected(false);
            }
        }

        if (q == 5) {
            Color as = q1.getBackground();
            a4.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("d) Brussels")) {
                    Color qw = q2.getBackground();

                    a4.setBackground(qw);
                    l1.setSelectedIndex(4);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a4.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a4.setSelected(false);
            }
        }
        if (q == 4) {
            Color as = q1.getBackground();
            a4.setBackground(as);
            int d = JOptionPane.showConfirmDialog(null, "Are You Sure?");
            if (d == JOptionPane.YES_OPTION) {

                if (ans.equalsIgnoreCase("d) Vint Cerf")) {
                    Color qw = q2.getBackground();

                    a4.setBackground(qw);
                    l1.setSelectedIndex(3);
                    JOptionPane.showMessageDialog(null, "Congratulations!\nYour Answer is Right"); sh();wr();

                } else {
                    Color qw = q3.getBackground();
                    a4.setBackground(qw);
                    l1.setSelectedIndex(9);
                    JOptionPane.showMessageDialog(null, "oops!\nYour Answer is Wrong");
                    qu.setVisible(false);r();wr();
                }

            } else {
                re();
                a4.setSelected(false);
            }
        }
    }//GEN-LAST:event_a4ActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed


        cr();
st.setVisible(false);
       re();
        a1.setSelected(false);
        a2.setSelected(false);
        a3.setSelected(false);
        a4.setSelected(false);

        a1.setText("A)");
        a2.setText("B)");
        a3.setText("C)");
        a4.setText("D)");


        int no = l1.getSelectedIndex();
        double a = Math.random();
        if (no == 9) {



            if (a < 0.20) {
                b1.setText("Q1) WHICH IS THE FIRST PROCESSOR OF INTEL?");
                a1.setText(a1.getText() + " INTEL 8008");
                a2.setText(a2.getText() + " INTEL 4004");//WRITE
                a3.setText(a3.getText() + " INTEL 4040");
                a4.setText(a4.getText() + " INTEL PENTIUM 1");
                o1=1;
            } else if (a > 0.20 && a < 0.40) {
                b1.setText("Q1) Which of the following cities is known as Electronic City of India ?");
                a1.setText(a1.getText() + " BANGALORE");//WRITE
                a2.setText(a2.getText() + " MADRAS");
                a3.setText(a3.getText() + " LUCKNOW");
                a4.setText(a4.getText() + " GURGAON");
                o1=2;
            } else if (a > 0.40 && a < 0.60) {
                b1.setText("Q1) Novel 'UP FROM SLAVERY' WAS WRITTEN BY WHOM ?");
                a1.setText(a1.getText() + " JAMES BOND");
                a2.setText(a2.getText() + " CHETAN BHAGAT");
                a3.setText(a3.getText() + " SHALINI SHARMA");
                a4.setText(a4.getText() + " BOOKER TERRIFERO WASHINGTON");//WRITE
                o1=3;
            } else if (a > 0.60 && a < 0.80) {
                b1.setText("Q1) WHICH OF THE FOLLOWING IS THE INDIA'S FASTEST SUPER COMPUTER ?");
                a1.setText(a1.getText() + " ANURAG");
                a2.setText(a2.getText() + " PARAM 10000");
                a3.setText(a3.getText() + " SANGARSH");//WRITE

                a4.setText(a4.getText() + " TIAHNE 2");
                o1=4;
            } else if (a > 0.80 && a < 1) {
                b1.setText("Q1) Which was the first word which was sent over the internet when first mail was sent ?");
                a1.setText(a1.getText() + " LO");//WRITE
                a2.setText(a2.getText() + " HI");
                a3.setText(a3.getText() + " HELLOW");
                a4.setText(a4.getText() + " WELCOME");
                o1=5;
            }
        }
        if (no == 8) {
            if (a < 0.20) {
                b1.setText("Q2) Dwayne Johnson's first leading film role was-?");
                a1.setText(a1.getText() + " The Scorpion King");//WRITE
                a2.setText(a2.getText() + " The Rundown");
                a3.setText(a3.getText() + " The Game Plan");
                a4.setText(a4.getText() + " Get Smart");
                o1=6;
            }
            if (a > 0.20 && a < 0.40) {
                b1.setText("Q2) WHEN WAS FIRST SERIES OF 'GRAND THEFT AUTO' WAS REALESED ?");
                a1.setText(a1.getText() + " DECEMBER 1998");
                a2.setText(a2.getText() + " JULY 1997");
                a3.setText(a3.getText() + " OCTOBER 1997");//WRITE
                a4.setText(a4.getText() + " JULY 1998");
                o1=7;
            }
            if (a > 0.40 && a < 0.60) {
                b1.setText("Q2) WHAT WAS THE SPEED OF SINGLE VACUUME TUBE ?");
                a1.setText(a1.getText() + " 2.2MHz");
                a2.setText(a2.getText() + " 1 MHz");//WRITE
                a3.setText(a3.getText() + " 3 KHz");
                a4.setText(a4.getText() + " 1 GHz");
                o1=8;
            }
            if (a > 0.60 && a < 0.80) {
                b1.setText("Q2) Which was the first free web-based email service. ?");
                a1.setText(a1.getText() + " FACEBOOK");
                a2.setText(a2.getText() + " GMAIL");
                a3.setText(a3.getText() + " HOTMAIL");//WRITE
                a4.setText(a4.getText() + " REDIFFMAIL");
                o1=9;
            }
            if (a > 0.80 && a < 1) {
                b1.setText("Q2) WHO WAS THE AUTHOR OF BOOK 'My experiments with Truth' ?");
                a1.setText(a1.getText() + " J K ROWLING ");
                a2.setText(a2.getText() + " RUSKEN BOND");
                a3.setText(a3.getText() + " JAWAHARLAL NEHRU");
                a4.setText(a4.getText() + " MAHATMA GANDHI");//WRITE
                o1=10;
            }
        }
        if (no == 7) {
            if (a < 0.20) {
                b1.setText("Q3) WHEN WAS 'FACEBOOK' WAS FOUNDED??");
                a1.setText(a1.getText() + " February 9, 2005");//WRITE
                a2.setText(a2.getText() + " February 4, 2004 ");
                a3.setText(a3.getText() + " MAY 4, 2003 ");
                a4.setText(a4.getText() + " February 14, 2004 ");
                o1=11;
            }
            if (a > 0.20 && a < 0.40) {
                b1.setText("Q3) WHERE IS THE HEADQUARTER OF GOOGLE IS SITUATED ?");
                a1.setText(a1.getText() + " JAPAN");
                a2.setText(a2.getText() + " NEW YORK");
                a3.setText(a3.getText() + " CALIFORNIA ");//WRITE
                a4.setText(a4.getText() + " INDIA");
                o1=12;
            }
            if (a > 0.40 && a < 0.60) {
                b1.setText("Q3) Who among the following bollywood actors has been conferred with the Honoured Guest \nof Texas award ?");
                a1.setText(a1.getText() + " AMITABH BACHHAN ");
                a2.setText(a2.getText() + " SHRI DEVI ");
                a3.setText(a3.getText() + " ANUPAM KHER");//WRITE
                a4.setText(a4.getText() + " SALMAN KHAN");
                o1=13;
            }
            if (a > 0.60 && a < 0.80) {
                b1.setText("Q3) Which of the following state was host of 10th World Hindi Conference ?");
                a1.setText(a1.getText() + " MADHYA PRADESH");//WRITE
                a2.setText(a2.getText() + " UTTAR PRADESH");
                a3.setText(a3.getText() + " HARYANA");
                a4.setText(a4.getText() + " ASSAAM");
                o1=14;
            }
            if (a > 0.80 && a < 1) {
                b1.setText("Q3) WHICH IS THE WORLD'S FASTEST CAR ?");
                a1.setText(a1.getText() + " McLaren F1");
                a2.setText(a2.getText() + " KOENIGSEGG AGERA R");
                a3.setText(a3.getText() + " LAMBORGHINI");
                a4.setText(a4.getText() + " HENNESSEY VENOM GT");//WRITE
                o1=15;
            }
        }
        if (no == 6) {
            if (a < 0.20) {
                b1.setText("Q4) WHICH OF THESE FILE SYSTEM ARE SUPPORTED BY WINDOWS 2000 ?");
                a1.setText(a1.getText() + " NTFS");
                a2.setText(a2.getText() + " FAT32");
                a3.setText(a3.getText() + " CDFS");
                a4.setText(a4.getText() + " ALL");//WRITE
                o1=16;
            }
            if (a > 0.20 && a < 0.40) {
                b1.setText("Q4) Speed Of Printer Is Generally Measured In ?");
                a1.setText(a1.getText() + " ppm");//WRITE
                a2.setText(a2.getText() + " pps");
                a3.setText(a3.getText() + " dpi");
                a4.setText(a4.getText() + " lps");
                o1=17;
            }
            if (a > 0.40 && a < 0.60) {
                b1.setText("Q4) Unit Used For Express Data Transmission Speed ?");
                a1.setText(a1.getText() + " KHz");
                a2.setText(a2.getText() + " MHZ");
                a3.setText(a3.getText() + " Bps");//WRITE
                a4.setText(a4.getText() + " GHz");
                o1=18;
            }
            if (a > 0.60 && a < 0.80) {
                b1.setText("Q4) LINT Is a ?");
                a1.setText(a1.getText() + " C COMPILER");
                a2.setText(a2.getText() + " DEBUGGER");
                a3.setText(a3.getText() + " C INTERPRETER");
                a4.setText(a4.getText() + " TOOL OF C");//WRITE
                o1=19;
            }
            if (a > 0.80 && a < 1) {
                b1.setText("Q4) INTEL 4040 IS MADE UP OF HOW MANY TRANSISTORS ?");
                a1.setText(a1.getText() + " 4,000");
                a2.setText(a2.getText() + " 6,500");
                a3.setText(a3.getText() + " 3,000");//WRITE
                a4.setText(a4.getText() + " 2,230");
                o1=20;
            }
        }
        if (no == 5) {
            if (a < 0.20) {
                b1.setText("Q5) The United Nations was founded on ?");
                a1.setText(a1.getText() + " March 24, 1945");
                a2.setText(a2.getText() + " October 24, 1945");//WRITE
                a3.setText(a3.getText() + " March 24, 1949");
                a4.setText(a4.getText() + " October 24, 1950");
                o1=21;
            }
            if (a > 0.20 && a < 0.40) {
                b1.setText("Q5) Which country from the following is NOT the member of UNO? ?");
                a1.setText(a1.getText() + " Vatican City");//WRITE
                a2.setText(a2.getText() + " Afghanistan");
                a3.setText(a3.getText() + " North Korea");
                a4.setText(a4.getText() + " Vaitnam");
                o1=22;
            }
            if (a > 0.40 && a < 0.60) {
                b1.setText("Q5) The International Court of Justice is located in ?");
                a1.setText(a1.getText() + " New York");
                a2.setText(a2.getText() + " Washigton");
                a3.setText(a3.getText() + " The Hague");//WRITE
                a4.setText(a4.getText() + " Geneva");
                o1=23;
            }
            if (a > 0.60 && a < 0.80) {
                b1.setText("Q5) The currency of Indonesia is ?");
                a1.setText(a1.getText() + " rupiah");//WRITE
                a2.setText(a2.getText() + " dinar");
                a3.setText(a3.getText() + " rangit");
                a4.setText(a4.getText() + " riyal");
                o1=24;
            }
            if (a > 0.80 && a < 1) {
                b1.setText("Q5) The headquarter of NATO is located in ?");
                a1.setText(a1.getText() + " New York");
                a2.setText(a2.getText() + " Paris");
                a3.setText(a3.getText() + " Geneva");
                a4.setText(a4.getText() + " Brussels");//WRITE
                o1=25;
            }
        }
        if (no == 4) {
            if (a < 0.20) {
                b1.setText("Q6) The motto of UNO is ?");
                a1.setText(a1.getText() + " It's your world!");//WRITE
                a2.setText(a2.getText() + " Life for All!");
                a3.setText(a3.getText() + " Peace!");
                a4.setText(a4.getText() + " Love and Peace!");
            }
            if (a > 0.20 && a < 0.40) {
                b1.setText("Q6) The world's highest mountain is in ?");
                a1.setText(a1.getText() + " China");
                a2.setText(a2.getText() + " Pakistan");
                a3.setText(a3.getText() + " Nepal");//WRITE
                a4.setText(a4.getText() + " India");
            }
            if (a > 0.40 && a < 0.60) {
                b1.setText("Q6) The headquarter of Red Cross is in ");
                a1.setText(a1.getText() + " New York");
                a2.setText(a2.getText() + " Washigton");
                a3.setText(a3.getText() + " Geneva");//WRITE
                a4.setText(a4.getText() + " The Hague");
            }
            if (a > 0.60 && a < 0.80) {
                b1.setText("Q6) Where was the first computer installed in India? ?");
                a1.setText(a1.getText() + " IIT,Mumbai");
                a2.setText(a2.getText() + " Indian Statistical Institute, Kolkata");//WRITE
                a3.setText(a3.getText() + " Indian Research Institute,Banglore");
                a4.setText(a4.getText() + " Computer And Research Intitue,delhi");
           }
            if (a > 0.80 && a < 1) {
                b1.setText("Q6) The fathers of the Internet is ?");
                a1.setText(a1.getText() + " Spark Knight");
                a2.setText(a2.getText() + " Johnson Peak");
                a3.setText(a3.getText() + " James Gill");
                a4.setText(a4.getText() + " Vint Cerf");//WRITE
            }
        }
        if (no == 3) {
            if (a < 0.20) {
                b1.setText("Q7) PDP-8 was the Computer of Which Generation?");
                a1.setText(a1.getText() + " 5th Gen");
                a2.setText(a2.getText() + " 2nd Gen");
                a3.setText(a3.getText() + " 3rd Gen");//WRITE
                a4.setText(a4.getText() + " 4th Gen");
            }
            if (a > 0.20 && a < 0.40) {
                b1.setText("Q7) First Game which is included in Windows is?");
                a1.setText(a1.getText() + " Solitaire");
                a2.setText(a2.getText() + " Pinball");
                a3.setText(a3.getText() + " Reversi");//WRITE
                a4.setText(a4.getText() + " Sant Que Lim");
            }
            if (a > 0.40 && a < 0.60) {
                b1.setText("Q7) ");
                a1.setText(a1.getText() + " ");
                a2.setText(a2.getText() + " ");
                a3.setText(a3.getText() + " ");//WRITE
                a4.setText(a4.getText() + " ");
            }
            if (a > 0.60 && a < 0.80) {
                b1.setText("Q7)  ?");
                a1.setText(a1.getText() + " ");//WRITE
                a2.setText(a2.getText() + " ");
                a3.setText(a3.getText() + " ");
                a4.setText(a4.getText() + " ");
            }
            if (a > 0.80 && a < 1) {
                b1.setText("Q7)  ?");
                a1.setText(a1.getText() + " ");
                a2.setText(a2.getText() + " ");
                a3.setText(a3.getText() + " ");
                a4.setText(a4.getText() + " ");//WRITE
            }
        }
}//GEN-LAST:event_stActionPerformed

    private void quActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quActionPerformed
        int y=JOptionPane.showConfirmDialog(null, "Are You Sure To Want Quit?");
        if(y==JOptionPane.YES_OPTION){
            wr();re();
            l1.setSelectedIndex(9);
            qu.setVisible(false);
            st.setVisible(true);
            st.setText("START");
        a1.setText("A)");
        a2.setText("B)");
        a3.setText("C)");
        a4.setText("D)");
        b1.setText("");}
        else{}
    }//GEN-LAST:event_quActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new KBC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton a3;
    private javax.swing.JRadioButton a4;
    private javax.swing.JLabel b1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList l1;
    private javax.swing.JDesktopPane m1;
    private javax.swing.JLabel q1;
    private javax.swing.JPanel q2;
    private javax.swing.JPanel q3;
    private javax.swing.JButton qu;
    private javax.swing.JButton st;
    // End of variables declaration//GEN-END:variables
class a{
public void exe()
{
    JOptionPane.showMessageDialog(null,"go to hell");
}
};
    private void re() {
        {
            Color af = m1.getBackground();
            a1.setBackground(af);
            a2.setBackground(af);
            a3.setBackground(af);
            a4.setBackground(af);
         a df = null;
         //df.exe();
        }
    }

    private void s() {
        {
            st.setText("NEXT");
        }
    }

    private void r() {
        {
            st.setVisible(true);
           st.setText("START");
        }
    }
    private void wr() {
        {
           a1.setEnabled(false);
            a2.setEnabled(false);
             a3.setEnabled(false);
              a4.setEnabled(false);
        }
    }
     private void cr() {
        
           a1.setEnabled(true);
            a2.setEnabled(true);
             a3.setEnabled(true);
              a4.setEnabled(true);
        
    }
     private void sh() {
        {
           st.setVisible(true);
        }
    }
}
